name: basics
favicon: null
layout_spectrum: 0.99782
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6a63d'
    - '#ffffff'
    - '#fdebdb'
    - '#f9c382'
    - '#fbd5ae'
  brandStrength: 1
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
